Userクラスの実装
wakatakeru/infoexpr2-bustra pull request #17
Opened 2017-11-07 11:52 UTC by closekn

## What - 内容説明
Userクラスの実装
keyListener, Map などの処理の確認
## Why - 背景
キー入力、スコア、ターゲット を可能にするため
## When - 期限
2017.11.11(土) 23:59
## Who, Where, How その他記載事項があれば
コード内にコメントとしてわからなかった要素など記述している。

2017-11-07 13:24 UTC, wakatakeru requested changes
何箇所か、うまく動作しなさげなところがあるので、仮のmainメソッドとか書いてみて、動くかどうか確認してみてください～😍

2017-11-07 13:24 UTC, wakatakeru commented on bustra/User.java
> +  public Map getPosition() {
ここでは、単にpositionの値を返却するだけでいいかも。
movePositionみたいなメソッドを別途で生やして、移動処理を書くべき？🤔

2017-11-07 13:24 UTC, wakatakeru commented on bustra/User.java
> +    score += getScore();
scoreにScoreクラスのgetPoint()メソッドの値を入れるだけで良いと思います！
`score = user_score.getPoint();`って感じになりそう。

2017-11-07 13:24 UTC, wakatakeru commented on bustra/User.java
> +
`User`は`Score`のインスタンスを持つので、インスタンスを生成しておきましょう！
scoreだと、privateの変数とかぶるから、user_scoreとかでどうでしょう？🤔

2017-11-07 13:24 UTC, wakatakeru commented on bustra/User.java
> +
ここちょっと、怪しい実装になりそうなので、意見募集します✋

2017-11-07 13:24 UTC, wakatakeru commented on bustra/User.java
> +  public int getHand(KeyEvent e) {
KeyPressした時に値帰ってきました？
仮のmainメソッドとか書いて、動作確かめてみてください！👊

2017-11-07 13:38 UTC, wakatakeru requested changes
誤字脱字と文法レベルのチェックだけしました！

2017-11-07 13:38 UTC, wakatakeru commented on bustra/User.java
> +﻿package bustra;
BOMがついてるみたいです！😨
BOM無しUTF-8に変換しておいてください！

2017-11-07 13:38 UTC, wakatakeru commented on bustra/User.java
> +      case default:  return 5;    // another key
`case default`ではなく、`default`だけですねー！

2017-11-07 13:38 UTC, wakatakeru commented on bustra/User.java
> +      case default: /* do not move */ break;
ここも、`case default`ではなく、`default`だけですね！

2017-11-07 13:38 UTC, wakatakeru commented on bustra/User.java
> +  private boolean setScore {
メソッドなので、メソッド名のあとに括弧が必要です！。`setScore()`とかになるかな？

2017-11-07 13:43 UTC, wakatakeru commented
変数 position についてなんですが、`position.put(x, 0)`ではなくて、`position.put("x", 0)`って感じですね！
Mapのキーは変数も取れてしまうので、xが変数として扱われてしまいます。
なんで、ここでは、文字列をキーにしましょう！

2017-11-08 03:08 UTC, closekn commented on bustra/User.java
> +
フィールドでインスタンスを生成するのと、コンストラクタでインスタンスを生成するのだと、どちらが良いと思われますか？

2017-11-08 10:03 UTC, wakatakeru commented on bustra/User.java
> +
フィールドでいいんじゃないかなあ？

2017-11-08 16:23 UTC, wakatakeru commented on bustra/User.java
> +
あ！ごめんなさい！フィールドじゃなくて、コンストラクタのほうがいいかもです！
変数の宣言だけはフィールドかなあ？と思います😘

2017-11-10 03:51 UTC, wakatakeru commented
ref #20 
Userクラスはキー入力を受け付けない方向で！😘

2017-11-10 04:15 UTC, wakatakeru requested changes

2017-11-10 04:15 UTC, wakatakeru commented on bustra/User.java
> -    addKeyListener(this);
お！よさそう！😘

2017-11-10 04:15 UTC, wakatakeru commented on bustra/User.java
> -  public int getHand(KeyEvent e) {
おー！これでBaseに管理を移管しましょう！😘

2017-11-10 04:21 UTC, wakatakeru requested changes
空行やキャメル/スネークの問題など、細かいところですが、よろしく！

2017-11-10 04:21 UTC, wakatakeru commented on bustra/User.java
ここの空行いらんかも？🤔

2017-11-10 04:21 UTC, wakatakeru commented on bustra/User.java
ここの空行もいらんかも？🤔

2017-11-10 04:21 UTC, wakatakeru commented on bustra/User.java
ここも空行いらなさそう？🤔

2017-11-10 04:21 UTC, wakatakeru commented on bustra/User.java
> +  private Score user_score;
キャメルケースにしましょう！😳

2017-11-10 04:21 UTC, wakatakeru commented on bustra/User.java
> +    user_score = new Score();
ここもキャメルケースで！😳

2017-11-10 04:21 UTC, wakatakeru commented on bustra/User.java
> +    score = user_score.getPoint();
ここもキャメルケースのほうが良さそうですね！😳

2017-11-11 00:13 UTC, closekn commented
PointクラスのgetX(),getY()メソッドの返り値がdouble型だったため使用をやめました。
また、privateメソッドであるsetScoreメソッドを呼び出す部分がUserクラス内に存在しなかったため、とりあえずgetScoreメソッド内に入れ、scoreをセットしてから返却するようにしました。

この状態で仮のmainを立てて動かしてみた結果、Userクラスとして機能したためレビューお願いします。

2017-11-11 06:50 UTC, wakatakeru commented
非常に良さそうな感じです！！！！！！！
特に、Pointクラスのプロパティx, yがpublicであることに着目した、値の更新、良いと思います！！！

2017-11-11 06:50 UTC, wakatakeru approved these changes

2017-11-11 06:53 UTC, wakatakeru commented
![](https://pbs.twimg.com/media/BpupqiBCcAEqfIz.png)

2017-11-11 06:54 UTC, merged