得点機能を追加する
wakatakeru/infoexpr2-bustra pull request #23
Opened 2017-11-11 14:31 UTC by nd3

## What - 内容説明
Scoreクラスを実装して、得点機能を追加する。
内部で計算を行うようにする。

## Why - 背景
元のゲームには得点機能がないため。
得点機能を追加することで、前回プレイ時の自分との比較や、他プレイヤーとの比較など、
ゲームをプレイして終わりにならないようにすることが目的。

## When - 期限
2017.11.15(水)

## Who, Where, How その他記載事項があれば

2017-11-12 05:52 UTC, wakatakeru requested changes
一部、処理の仕方を変えたほうが良さそうな部分がいくつかありました！
得点計算のルールは、個人的には、@nd3の策定したルールが良さそうな感じがあります！！💘

2017-11-12 05:52 UTC, wakatakeru commented on bustra/Score.java
> +    private int calcPoint() {
calcPointは、返り値無しの方がいいかも！
っていうのも、これだと、getPoint()メソッドがあってもなくても関係なくなっちゃいそうかなーって思いました！😳

2017-11-12 05:52 UTC, wakatakeru commented on bustra/Score.java
> +        return calcPoint();
ここは、
プロパティ`point`を返却する
って処理の方が良いかもです！

calcPointメソッドはBaseのほうで呼ぶことになると思います！

2017-11-12 05:52 UTC, wakatakeru commented on bustra/Score.java
> +	point = getErasedBlockCount() * getErasingCount() / 2 * 100;
ref: #19 
この得点計算ルール、非常に良いと思います！💘
ただ、getErasedBlockCount()では、Boardのメソッドを呼び出すことができないので、
`calcPoint()`は、`calcPoint(erasedBlockCount, erasingCount)`のように、
引数を取って計算する形がいいかもしれませんね。
これなら、別のクラスからも値渡せますし！🙆

2017-11-13 00:46 UTC, wakatakeru requested changes
getPointは、calcPointが走っているかどうかに関わらず、`return point`するだけで大丈夫だと思います！😘

2017-11-13 00:46 UTC, wakatakeru commented on bustra/Score.java
> +        point = calcPoint(getErasedBlockCount(),  getErasingCount());
この行は必要無いかも〜。
というのも、calcPointは、Userクラスなり、Baseクラスからなり呼ぶことになる可能性が高いからです！👯

2017-11-13 00:47 UTC, nd3 commented
Scoreクラスで実装すべき処理って他にありそうですか？　例えばcalcPoint()でこの計算が要るとか、このメソッドも実は要るとか

2017-11-13 00:48 UTC, wakatakeru commented
Scoreクラスは、とりあえずこれで大丈夫だと思います！！

2017-11-13 00:50 UTC, nd3 commented on bustra/Score.java
> +        point = calcPoint(getErasedBlockCount(),  getErasingCount());
修正しました！

2017-11-13 00:51 UTC, nd3 commented
ありがとうございます❕
処理が足りないことはないか心配だったので^^;

2017-11-13 00:53 UTC, wakatakeru commented
だいじょうぶですよ！ちなみに、作業これで大丈夫そうなら、In Reviewにラベル変えておくといいかもです！

2017-11-13 00:56 UTC, wakatakeru requested changes
アクセス修飾子について変更が必要そうです！

2017-11-13 00:56 UTC, wakatakeru commented on bustra/Score.java
> +    public int getPoint() {
ここは、同じパッケージ内からしか参照されないので、`public`ではなく、`protected`のほうがいいかもですね！😘

2017-11-13 00:56 UTC, wakatakeru commented on bustra/Score.java
> +    private int calcPoint(int erasedBlockCount, int erasingCount) {
ここは、別のクラスから参照される && 参照されるのは同一パッケージ なので、`private`ではなく、`protected`のほうが良さそうですね！👯

2017-11-13 01:02 UTC, nd3 commented on bustra/Score.java
> +    private int calcPoint(int erasedBlockCount, int erasingCount) {
修正しました！

2017-11-13 01:04 UTC, wakatakeru commented on bustra/Score.java
> +    private int calcPoint(int erasedBlockCount, int erasingCount) {
確認しました！ちなみに、getPointメソッドの方はどうしますか？

2017-11-13 01:12 UTC, nd3 commented
変更見落としてました
修正完了です！

2017-11-13 01:13 UTC, wakatakeru approved these changes

2017-11-13 01:14 UTC, merged

2017-11-13 01:15 UTC, wakatakeru commented
とても良い感じだと思います！！！
よさそう！！！

![](http://otiai10.com/chino.gif)