ゲーム仕様書としてのREADMEファイルの編集
wakatakeru/infoexpr2-bustra pull request #29
Opened 2017-11-15 14:13 UTC by closekn

## What - 内容説明
etc/README.md を編集
## Why - 背景
作成したゲームを理解してもらうため
## When - 期限
いつでも
## その他
足りない項目がある・ここの表現はおかしい・追加で記述してほしいことがある
など、どんどん意見ください

2017-11-15 14:34 UTC, wakatakeru reviewed
このファイルそのものも、`/etc`の下ではなくて、`/`に直接置いてもいいかもです！

2017-11-15 14:34 UTC, wakatakeru commented on etc/README.md
> +
ここに実行方法が書いてあるとめっちゃ良さそう！

2017-11-16 06:17 UTC, nd3 reviewed
得点の算出方法ってここに記すべきですかね？　いらなければこのままでも問題なさそうな気がします！
あとは、スコアランキングがめでたく実装(別プロジェクト)されれば、その説明を加えるくらいだと思います。In Reviewの段階だと思います！

2017-11-16 06:21 UTC, wakatakeru commented
得点の算出方法についても、少し触れる程度書いておくといいかもですね！
スコアサーバについては、少々実装の可否をお待ち下さい…😅

2017-11-16 06:29 UTC, wakatakeru reviewed
大筋はとてもいい感じだと思います！🎉
少々手直しが必要なところがあるので、確認よろしくおねがいします！

2017-11-16 06:29 UTC, wakatakeru commented on README.md
> +  - コマンドライン上での移動
`移動`は`起動`の間違いかな…？🤔

2017-11-16 06:29 UTC, wakatakeru commented on README.md
> +
実際には、`閉じる`の画像以外も使われていたので、`無料素材サービス (https://sozai.cman.jp)`って感じに紹介するといいかも？

2017-11-16 06:29 UTC, wakatakeru commented on README.md
> +制限時間内で多くのブロックを消してスコアを稼ぐパズルゲームです。
制限時間が具体的に何分か書いておいたほうが良さげかも。ひとまず`3分`にしておきましょう。

2017-11-16 06:29 UTC, wakatakeru commented on README.md
> +同じ色のブロックが横に3つ並べることでブロックを消すことができます。
`同じ色のブロックが横に3つ並べること`とありますが、`同じ色のブロックを横に3つ並べること`のほうがいいかもですね。

2017-11-16 06:29 UTC, wakatakeru commented on README.md
> +
算出方法を書いておくと良さそう！

2017-11-20 02:01 UTC, closekn commented
制限時間の確定後の修正と素材確定後の記述追加を除けばこれで完成と思います。
修正案・提案あればお願いします。

2017-11-20 02:24 UTC, wakatakeru requested changes
大筋はこれで大丈夫だと思います！
少しだけ修正してほしいところがあるので、確認よろしくおねがいします！

2017-11-20 02:24 UTC, wakatakeru commented on README.md
> +`protecred static final String URL = "http://<スコアサーバのアドレス>/scores/create"`
URLについては、書き換え箇所が二箇所あったような？🤔
たしか、スコアサーバへのPOST用のURLである定数`URL`と、
順位の一覧ページへのURLである、`ROOT_URL`だったかな？
どっちも書き換えたほうがいいとおもいます！

2017-11-20 02:24 UTC, wakatakeru commented on README.md
> +スコアサーバをどこで走らせるかによって不定です。
ここは、`bustra/Constants.javaに、スコアサーバのアドレスが記載されています。標準では、localhostの3000番ポートとなっています。`とかのほうがいいかも。

2017-11-20 02:24 UTC, wakatakeru commented on README.md
> +ゲーム終了後にスコアサーバにスコアを送信することで、他のプレイヤーとランキングで競うことができます。
スコアサーバのリポジトリがどこにあるか、明記したほうがいいかもしれませんねー
具体的には、`https://github.com/wakatakeru/infoexpr2-bustra-score_server`ですね！

2017-11-20 02:24 UTC, wakatakeru commented on README.md
> +以下の動作はディレクトリ infoexpr2-bustra 下で行う。
めっちゃ細かいけど、`行う`よりも`行います`のほうが、統一感あっていいかもね。
ここから下の作業の列挙は、文体もこのままで大丈夫だと思います。

2017-11-20 02:24 UTC, wakatakeru commented on README.md
> +## 参考
issueとかに、参考にしたページ情報がころがっているかも…ちょっと調査してみてください！

2017-11-20 02:24 UTC, wakatakeru commented on README.md
> +一回のブロック操作で消えたブロックの数と消した回数に応じてスコアにボーナスが付きます。
ここの説明は、数式入れてもいいかもしれません…🤔
`消えたブロックの数 × 1度の操作で消えた連の数 / 2 * 100`とかって書いとくといいかもです！
(数式の文章は、もっといい感じなのがありそうではあります)

2017-11-20 02:38 UTC, closekn commented on README.md
> +ゲーム終了後にスコアサーバにスコアを送信することで、他のプレイヤーとランキングで競うことができます。
本実験のgithubのページも載せた方がよいでしょうか？
それなら、それらを乗せる新しい欄を用意しようと思うのですが...

2017-11-20 09:42 UTC, kohshow approved these changes
仕様書として問題ないと思います！

2017-11-20 10:30 UTC, wakatakeru approved these changes

2017-11-20 10:32 UTC, merged

2017-11-20 10:33 UTC, wakatakeru commented
[![LGTM](https://lgtm.in/p/oYmIBc2Qp)](https://lgtm.in/i/oYmIBc2Qp)